name: iOS CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:

  lint-format:
    name: SwiftLint & SwiftFormat
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          brew install swiftlint
          brew install swiftformat

      - name: SwiftFormat check
        run: swiftformat . --lint

      - name: SwiftLint check
        run: swiftlint

  build-test:
    name: Build & Test
    runs-on: macos-latest
    needs: lint-format

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve SPM
        run: xcodebuild -resolvePackageDependencies

      - name: Build
        run: |
          xcodebuild build \
          -project Swift-Concurrency.xcodeproj \
          -scheme Swift-Concurrency \
          -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -project Swift-Concurrency.xcodeproj \
          -scheme Swift-Concurrency \
          -destination 'platform=iOS Simulator,name=iPhone 15'

  security-basic:
    name: Security & Dependency checks
    runs-on: macos-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v4

      - name: SPM dependency graph
        run: swift package show-dependencies
